/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.*;

import java.awt.event.ActionEvent;
import Controller.EmpruntController;

import javax.swing.*;
/**
 *
 * @author Kevin
 */
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.table.DefaultTableModel;
import java.awt.Dialog.ModalExclusionType;
import java.awt.Window.Type;
public class EmpruntGui extends javax.swing.JFrame {

    private JTable jtable1; // The table displayed on the GUI
    private EmpruntController EmpruntController = null;

    public EmpruntGui() {
    	setType(Type.POPUP);
    	setAlwaysOnTop(true);
    	setModalExclusionType(ModalExclusionType.APPLICATION_EXCLUDE);
    	getContentPane().setBackground(Color.WHITE);
        
        // This method creates the labels and text fields on the GUI
        initComponents();
        
        // Creates a controller for the table
        EmpruntController = new EmpruntController(this);

        // Add a table JTable to the GUI
        addJTable();

    }
    
    public void addJTable() {
        // Add the data and column names to a JTable
    	 jtable1 = new JTable(EmpruntController.getTableModel());
         jtable1.setFont(new Font("Times New Roman", Font.PLAIN, 11));
         jtable1.setBackground(Color.LIGHT_GRAY);
     
         // Add a ListSelectionListener to the table
         jtable1.getSelectionModel().addListSelectionListener(EmpruntController);
         
         // Add the table to a scrollpane
         JScrollPane scrollpane = new JScrollPane(jtable1);
         
         // Create a window
         // This was originally jPanel
         jPanel2.setLayout(new BorderLayout());
         jPanel2.add(scrollpane, BorderLayout.CENTER);

         // User can only select one row at a time
         jtable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    // Update the JTable
    public void updateTable() {
        jtable1.setModel(EmpruntController.getTableModel());
    }

    // Set data on the courseNameTextField
    public void setCourseNameTextField(String i) {
        courseNameTextField.setText(i);
    }

    // Set data on the courseNumberTextField
    public void setCourseNumberTextField(String value) { courseNumberTextField.setText(value); }

    // Set data on the enrollmentTextField
    public void setEnrollmentTextField(String num) {
        enrollmentTextField.setText(num);
    }

    // Set data on the startDateTextField
    public void setStartDateTextField(String startDate) {
        startDateTextField.setText(startDate);
    }

    // Set data on the endDateTextField
    public void setEndDateTextField(String endDate) {
        endDateTextField.setText(endDate);
    }
    public void setTextField(String startDate) {
        textField.setText(startDate);
    }
    public void setTextField1(String startDate) {
        textField_1.setText(startDate);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel1.setForeground(new Color(255, 175, 175));
        jPanel1.setBackground(Color.WHITE);
        courseNameLabel = new javax.swing.JLabel();
        courseNameLabel.setFont(new Font("Tahoma", Font.BOLD, 12));
        courseNumberLabel = new javax.swing.JLabel();
        courseNumberLabel.setFont(new Font("Tahoma", Font.BOLD, 12));
        enrollmentLabel = new javax.swing.JLabel();
        enrollmentLabel.setFont(new Font("Tahoma", Font.BOLD, 12));
        startDateLabel = new javax.swing.JLabel();
        endDateLabel = new javax.swing.JLabel();
        endDateLabel.setFont(new Font("Tahoma", Font.BOLD, 12));
        courseNameTextField = new javax.swing.JTextField();
        courseNameTextField.setBackground(Color.WHITE);
        courseNameTextField.setForeground(Color.BLACK);
        courseNumberTextField = new javax.swing.JTextField();
        enrollmentTextField = new javax.swing.JTextField();
        endDateTextField = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
         quitButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        courseListLabel = new javax.swing.JLabel();

        // Program will terminate when the window is closed
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        courseNameLabel.setText("Numero d'emprunt");

        courseNumberLabel.setText("Numero d'Exemplaire");

        enrollmentLabel.setText("Date d'Emprunt");


        endDateLabel.setText("Date de Retour");

        // Details for the Add button
        addButton.setText("Ajouter");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        // Details for the Delete button
        deleteButton.setText("Supprimer");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        // Details for the Update button
        updateButton.setText("Modifier");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });
        quitButton.setText("Quitter");
        quitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	quitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 432, Short.MAX_VALUE)
        );
        
        textField = new JTextField();
        
        endDateLabel_1 = new JLabel();
        endDateLabel_1.setFont(new Font("Tahoma", Font.BOLD, 12));
        endDateLabel_1.setText("Numero d'Adherent");
        
        textField_1 = new JTextField();
        
        endDateLabel_2 = new JLabel();
        endDateLabel_2.setFont(new Font("Tahoma", Font.BOLD, 12));
        endDateLabel_2.setText("Dure\u00E9 Maximale");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1Layout.setHorizontalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addComponent(quitButton)
        					.addContainerGap(999, Short.MAX_VALUE))
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addComponent(jPanel2, GroupLayout.DEFAULT_SIZE, 1056, Short.MAX_VALUE)
        					.addContainerGap())
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
        							.addComponent(endDateLabel_2, GroupLayout.PREFERRED_SIZE, 107, GroupLayout.PREFERRED_SIZE)
        							.addPreferredGap(ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
        							.addComponent(textField_1, GroupLayout.PREFERRED_SIZE, 302, GroupLayout.PREFERRED_SIZE))
        						.addGroup(jPanel1Layout.createSequentialGroup()
        							.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        								.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        									.addGroup(jPanel1Layout.createSequentialGroup()
        										.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
        											.addComponent(courseNameLabel, Alignment.LEADING)
        											.addComponent(enrollmentLabel, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        											.addComponent(courseNumberLabel, Alignment.LEADING, GroupLayout.PREFERRED_SIZE, 140, GroupLayout.PREFERRED_SIZE))
        										.addGap(107))
        									.addGroup(jPanel1Layout.createSequentialGroup()
        										.addComponent(endDateLabel, GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        										.addPreferredGap(ComponentPlacement.RELATED)))
        								.addGroup(jPanel1Layout.createSequentialGroup()
        									.addComponent(endDateLabel_1, GroupLayout.PREFERRED_SIZE, 120, GroupLayout.PREFERRED_SIZE)
        									.addPreferredGap(ComponentPlacement.RELATED)))
        							.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        								.addComponent(textField, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 302, GroupLayout.PREFERRED_SIZE)
        								.addGroup(Alignment.TRAILING, jPanel1Layout.createParallelGroup(Alignment.LEADING, false)
        									.addComponent(courseNameTextField)
        									.addComponent(courseNumberTextField, 302, 302, Short.MAX_VALUE)
        									.addComponent(enrollmentTextField, 302, 302, Short.MAX_VALUE)
        									.addComponent(endDateTextField, 302, 302, Short.MAX_VALUE)))))
        					.addGap(416)
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING, false)
        						.addComponent(updateButton, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        						.addComponent(addButton, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        						.addComponent(deleteButton, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        					.addGap(20))))
        );
        jPanel1Layout.setVerticalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING, false)
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addGap(27)
        					.addComponent(addButton)
        					.addGap(53)
        					.addComponent(deleteButton)
        					.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        					.addComponent(updateButton)
        					.addGap(1))
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addContainerGap()
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(courseNameTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        						.addComponent(courseNameLabel))
        					.addGap(18)
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(courseNumberTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        						.addComponent(courseNumberLabel))
        					.addGap(18)
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(enrollmentTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        						.addComponent(enrollmentLabel))
        					.addGap(18)
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(endDateTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        						.addComponent(endDateLabel))
        					.addGap(18)
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(textField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        						.addComponent(endDateLabel_1))
        					.addGap(18)))
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(textField_1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(endDateLabel_2))
        			.addGap(18)
        			.addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addGap(18)
        			.addComponent(quitButton)
        			.addGap(23))
        );
        jPanel1.setLayout(jPanel1Layout);

        courseListLabel.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        courseListLabel.setText("Gestion Emprunt/Retour");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(18)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(courseListLabel))
        			.addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(courseListLabel)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, 738, Short.MAX_VALUE)
        			.addContainerGap())
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Code for the add button
    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        String[] array = new String[jtable1.getColumnCount()];
        array[0] = courseNameTextField.getText();
        array[1] = courseNumberTextField.getText();
        array[2] = enrollmentTextField.getText();
        array[3] = endDateTextField.getText();
        array[4] = textField.getText();
        array[5] = textField_1.getText();
        // Send data to the controller to add it to the model
        EmpruntController.addRow(array);
    }//GEN-LAST:event_addButtonActionPerformed
	private void quitButtonActionPerformed(ActionEvent evt) {
		JFrame frame = null;
		// TODO Auto-generated method stub
		System.exit(0);;
	}
    // Code for the delete button
    // NEED TO FINISH MAKING THIS. SEE addRow() METHODS IN
    // CourseListTableController.java (LINE 65) and CouseListTableModel.java (LINE 149)
    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        String[] array = new String[jtable1.getColumnCount()];
        array[0] = courseNameTextField.getText();
        array[1] = courseNumberTextField.getText();
        array[2] = enrollmentTextField.getText();
        array[3] = endDateTextField.getText();
        array[4] = textField.getText();
        array[5] = textField_1.getText();
        // Send data to the controller to remove it from the model
        EmpruntController.deleteRow(array);
    }//GEN-LAST:event_deleteButtonActionPerformed

    // Code for the update button
    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
        String[] array = new String[jtable1.getColumnCount()];
        array[0] = courseNameTextField.getText();
        array[1] = courseNumberTextField.getText();
        array[2] = enrollmentTextField.getText();
        array[3] = endDateTextField.getText();
        array[4] = textField.getText();
        array[5] = textField_1.getText();
        // Send data to the controller to update it in the model
        EmpruntController.updateRow(array, jtable1);
    }//GEN-LAST:event_updateButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmpruntGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmpruntGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmpruntGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmpruntGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmpruntGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JLabel courseListLabel;
    private javax.swing.JLabel courseNameLabel;
    private javax.swing.JTextField courseNameTextField;
    private javax.swing.JLabel courseNumberLabel;
    private javax.swing.JTextField courseNumberTextField;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel endDateLabel;
    private javax.swing.JTextField endDateTextField;
    private javax.swing.JLabel enrollmentLabel;
    private javax.swing.JTextField enrollmentTextField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton quitButton;
    private javax.swing.JLabel startDateLabel;
    private javax.swing.JTextField startDateTextField;
    private javax.swing.JButton updateButton;
    private JTextField textField;
    private JLabel endDateLabel_1;
    private JTextField textField_1;
    private JLabel endDateLabel_2;
}
